# Generated by Django 3.2.25 on 2025-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('todo', 'Not Started'), ('active', 'In Progress'), ('done', 'Completed')], default='todo', max_length=20, null=True),
        ),
    ]
