# Generated by Django 5.2 on 2025-05-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
        ('tasks', '0002_alter_assignment_id_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
