# Generated by Django 5.2 on 2025-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_userid_alter_task_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='statusId',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
