# Generated by Django 3.2.25 on 2025-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_projectid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_user_assignment'),
        ),
    ]
