# Generated by Django 3.2.25 on 2025-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_assignment_unique_task_user_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
